Added in ability to disable autoscaling on tables

diff --git a/autoscale-toggle-sh b/autoscale-toggle-sh
--- a/autoscale-toggle-sh
+++ b/autoscale-toggle-sh
@@ -11,7 +11,7 @@ read_metric_type="DynamoDBReadCapacityUtilization"
 
 usage()
 {
-  echo "Usage: $0 [-a <role name>] [-p <table prefix>] [-m <min throughput>] [-x <max throughput>]" 1>&2
+  echo "Usage: $0 [-m <enable|disable>] [-r <role name>] [-p <table prefix>] [-i <min throughput>] [-x <max throughput>]" 1>&2
   exit 1
 }
 
@@ -88,6 +88,25 @@ register_scalable_target()
   fi
 }
 
+deregister_scalable_target()
+{
+  table_name=$1
+  scalable_dimension=$2
+
+  aws application-autoscaling deregister-scalable-target \
+    --service-namespace dynamodb \
+    --resource-id "table/${table_name}" \
+    --scalable-dimension "${scalable_dimension}"
+
+  status=$?
+
+  if [ ${status} -eq 0 ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
 scaling_policy_exists()
 {
   table_name=$1
@@ -108,7 +127,7 @@ scaling_policy_exists()
   fi
 }
 
-register_scaling_policy()
+put_scaling_policy()
 {
   table_name=$1
   metric_type=$2
@@ -138,6 +157,29 @@ EOF
   fi
 }
 
+delete_scaling_policy()
+{
+  table_name=$1
+  metric_type=$2
+  scalable_dimension=$3
+
+  policy_name=$(get_policy_name $table_name $metric_type)
+
+  aws application-autoscaling delete-scaling-policy \
+    --service-namespace dynamodb \
+    --resource-id "table/${table_name}" \
+    --scalable-dimension "${scalable_dimension}" \
+    --policy-name "${policy_name}"  > /dev/null
+
+  status=$?
+
+  if [ ${status} -eq 0 ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
 get_policy_name()
 {
   table_name=$1
@@ -150,15 +192,18 @@ get_policy_name()
 # ====== MAIN
 # ======================
 
-while getopts ":r:p:m:x:" o; do
+while getopts ":m:r:p:i:x:" o; do
     case "${o}" in
+        m)
+            mode=${OPTARG}
+            ;;
         r)
             rolename=${OPTARG}
             ;;
         p)
             prefix=${OPTARG}
             ;;
-        m)
+        i)
             min_tput=${OPTARG}
             ;;
         x)
@@ -171,8 +216,14 @@ while getopts ":r:p:m:x:" o; do
 done
 shift $((OPTIND-1))
 
-if [ -z "${rolename}" ] || [ -z "${prefix}" ] || [ -z "${min_tput}" ] || [ -z "${max_tput}" ]; then
-    usage
+if [ -z "${mode}" ] || [ -z "${rolename}" ] || [ -z "${prefix}" ] || [ -z "${min_tput}" ] || [ -z "${max_tput}" ]; then
+  usage
+fi
+
+if [ "${mode}" == "enable" ] || [ "${mode}" == "disable" ] ; then
+  echo "Running in ${mode} mode"
+else
+  usage
 fi
 
 # Main logic
@@ -185,53 +236,105 @@ if [[ "${role_arn}" != "false" ]]; then
 
   for table_name in "${table_array[@]}"
   do
-    echo -n "checking for scalable target (read throughput) for ${table_name} ..."
+    echo -n "checking for scalable target (read throughput) for ${table_name}..."
     if [[ "$(scalable_target_exists ${table_name} ${scaleable_read_dimension})" == "true" ]]; then
-      echo "FOUND"
-    else
-      echo -n "CREATING...."
-      if [[ "$(register_scalable_target ${table_name} ${scaleable_read_dimension} ${role_arn} ${min_tput} ${max_tput})" == "true" ]]; then
-        echo "DONE"
+      if [ "${mode}" == "disable" ]; then
+        echo -n "DISABLING...."
+        if [[ "$(deregister_scalable_target ${table_name} ${scaleable_read_dimension})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
       else
-        echo "ERROR"
+        echo "FOUND"
+      fi
+    else
+      if [ "${mode}" == "enable" ]; then
+        echo -n "CREATING...."
+        if [[ "$(register_scalable_target ${table_name} ${scaleable_read_dimension} ${role_arn} ${min_tput} ${max_tput})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
+      else
+        echo "NOT FOUND"
       fi
     fi
 
-    echo -n "checking for scalable target (write throughput) for ${table_name} ..."
+    echo -n "checking for scalable target (write throughput) for ${table_name}..."
     if [[ "$(scalable_target_exists ${table_name} ${scaleable_write_dimension})" == "true" ]]; then
-      echo "FOUND"
-    else
-      echo -n "CREATING..."
-      if [[ "$(register_scalable_target ${table_name} ${scaleable_write_dimension} ${role_arn} ${min_tput} ${max_tput})" == "true" ]]; then
-        echo "DONE"
+      if [ "${mode}" == "disable" ]; then
+        echo -n "DISABLING...."
+        if [[ "$(deregister_scalable_target ${table_name} ${scaleable_write_dimension})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
       else
-        echo "ERROR"
+        echo "FOUND"
+      fi
+    else
+      if [ "${mode}" == "enable" ]; then
+        echo -n "CREATING..."
+        if [[ "$(register_scalable_target ${table_name} ${scaleable_write_dimension} ${role_arn} ${min_tput} ${max_tput})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
+      else
+        echo "NOT FOUND"
       fi
     fi
 
     # Once we have the scalable targets, we can see if the scaling policies exist
-    echo -n "checking for scaling policy (read throughput) for ${table_name} ..."
+    echo -n "checking for scaling policy (read throughput) for ${table_name}..."
     if [[ "$(scaling_policy_exists ${table_name} ${read_metric_type})" == "true" ]]; then
-      echo "FOUND"
-    else
-      echo -n "CREATING..."
-      if [[ "$(register_scaling_policy ${table_name} ${read_metric_type} ${scaleable_read_dimension})" == "true" ]]; then
-        echo "DONE"
+      if [ "${mode}" == "disable" ]; then
+        echo -n "DISABLING...."
+        if [[ "$(delete_scaling_policy ${table_name} ${read_metric_type} ${scaleable_read_dimension})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
       else
-        echo "ERROR"
+        echo "FOUND"
+      fi
+    else
+      if [ "${mode}" == "enable" ]; then
+        echo -n "CREATING..."
+        if [[ "$(put_scaling_policy ${table_name} ${read_metric_type} ${scaleable_read_dimension})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
+      else
+        echo "NOT FOUND"
       fi
     fi
 
     # Once we have the scalable targets, we can see if the scaling policies exist
-    echo -n "checking for scaling policy (write throughput) for ${table_name} ..."
+    echo -n "checking for scaling policy (write throughput) for ${table_name}..."
     if [[ "$(scaling_policy_exists ${table_name} ${write_metric_type})" == "true" ]]; then
-      echo "FOUND"
-    else
-      echo -n "CREATING..."
-      if [[ "$(register_scaling_policy ${table_name} ${write_metric_type} ${scaleable_write_dimension})" == "true" ]]; then
-        echo "DONE"
+      if [ "${mode}" == "disable" ]; then
+        echo -n "DISABLING...."
+        if [[ "$(delete_scaling_policy ${table_name} ${write_metric_type} ${scaleable_write_dimension})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
       else
-        echo "ERROR"
+        echo "FOUND"
+      fi
+    else
+      if [ "${mode}" == "enable" ]; then
+        echo -n "CREATING..."
+        if [[ "$(put_scaling_policy ${table_name} ${write_metric_type} ${scaleable_write_dimension})" == "true" ]]; then
+          echo "DONE"
+        else
+          echo "ERROR"
+        fi
+      else
+        echo "NOT FOUND"
       fi
     fi
   done
